when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
    webpack_encore:
        output_path: '%kernel.project_dir%/public/build'
    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
